<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css"href="css/Recuperacion.css">
    <title>Actividad Base de Datos</title>
</head>
<body>

<div id="Marca-Jminnovation">
    <div class="logo-item">jd</div>
   </div>
  </br>
  <div class="B">
    <div class="c1"></div>
    <div class="c1"></div>
    <div class="c1"></div>
  </div>

<section class="form-register">

    <h4>Recupera tu Contraseña</h4>
<form>
     <label for="nombre">Usuario:</label>
    <input class="controls" type="text" name="Usuario"placeholder="Ingrese su Usuario" required>

    <label for="Correo">Correo Registrado:</label>
    <input class="controls" type="text" name="Correo" id="Correo" placeholder="Ingrese su Correo">

    
    <label for="NClave"> Nueva Contraseña:</label>
    <input class="controls" type="password" name="NClave"  placeholder="Ingrese su Contraseña"required>

    <label for="CClave"> Confirma tu Contraseña:</label>
    <input class="controls" type="password" name="CClave"  placeholder="Ingrese su Contraseña"required>
    
    <a href="Login-jd.php"id="bo">Enviar</button>
    
</form>

</section>


</body>
</html>